# Generated by Django 4.2.23 on 2025-08-20 12:11

import core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="client",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Client",
                "verbose_name_plural": "Clients",
            },
        ),
        migrations.AlterModelOptions(
            name="inquiry",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Inquiry",
                "verbose_name_plural": "Inquiries",
            },
        ),
        migrations.AlterModelOptions(
            name="jobcard",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Job Card",
                "verbose_name_plural": "Job Cards",
            },
        ),
        migrations.AlterModelOptions(
            name="renewal",
            options={
                "ordering": ["due_date"],
                "verbose_name": "Renewal",
                "verbose_name_plural": "Renewals",
            },
        ),
        migrations.AlterField(
            model_name="client",
            name="city",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="client",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="email",
            field=models.EmailField(
                blank=True, db_index=True, max_length=254, null=True
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="full_name",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="client",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="mobile",
            field=models.CharField(
                db_index=True,
                max_length=10,
                unique=True,
                validators=[core.validators.validate_mobile_number],
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="inquiry",
            name="city",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="inquiry",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="inquiry",
            name="email",
            field=models.EmailField(
                blank=True, db_index=True, max_length=254, null=True
            ),
        ),
        migrations.AlterField(
            model_name="inquiry",
            name="mobile",
            field=models.CharField(
                db_index=True,
                max_length=10,
                validators=[core.validators.validate_mobile_number],
            ),
        ),
        migrations.AlterField(
            model_name="inquiry",
            name="name",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="inquiry",
            name="service_interest",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="inquiry",
            name="status",
            field=models.CharField(
                choices=[
                    ("New", "New"),
                    ("Contacted", "Contacted"),
                    ("Converted", "Converted"),
                    ("Closed", "Closed"),
                ],
                db_index=True,
                default="New",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="inquiry",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="jobcard",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jobcards",
                to="core.client",
            ),
        ),
        migrations.AlterField(
            model_name="jobcard",
            name="code",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=20,
                unique=True,
                validators=[core.validators.validate_job_code],
            ),
        ),
        migrations.AlterField(
            model_name="jobcard",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="jobcard",
            name="grand_total",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=15,
                validators=[core.validators.validate_positive_decimal],
            ),
        ),
        migrations.AlterField(
            model_name="jobcard",
            name="next_service_date",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="jobcard",
            name="payment_status",
            field=models.CharField(
                choices=[("Unpaid", "Unpaid"), ("Paid", "Paid")],
                db_index=True,
                default="Unpaid",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="jobcard",
            name="price_subtotal",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=15,
                validators=[core.validators.validate_positive_decimal],
            ),
        ),
        migrations.AlterField(
            model_name="jobcard",
            name="schedule_date",
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name="jobcard",
            name="service_type",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="jobcard",
            name="status",
            field=models.CharField(
                choices=[
                    ("Enquiry", "Enquiry"),
                    ("WIP", "WIP"),
                    ("Done", "Done"),
                    ("Hold", "Hold"),
                    ("Cancel", "Cancel"),
                    ("Inactive", "Inactive"),
                ],
                db_index=True,
                default="Enquiry",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="jobcard",
            name="tax_percent",
            field=models.PositiveIntegerField(
                default=18, validators=[core.validators.validate_tax_percent]
            ),
        ),
        migrations.AlterField(
            model_name="jobcard",
            name="technician_name",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="jobcard",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="renewal",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="renewal",
            name="due_date",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
        ),
        migrations.AlterField(
            model_name="renewal",
            name="status",
            field=models.CharField(
                choices=[("Due", "Due"), ("Completed", "Completed")],
                db_index=True,
                default="Due",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="renewal",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name="client",
            index=models.Index(
                fields=["full_name", "mobile"], name="core_client_full_na_6a68e6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="client",
            index=models.Index(
                fields=["city", "is_active"], name="core_client_city_d3dc61_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inquiry",
            index=models.Index(
                fields=["status", "city"], name="core_inquir_status_1ae09a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inquiry",
            index=models.Index(
                fields=["mobile", "email"], name="core_inquir_mobile_cf6acc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobcard",
            index=models.Index(
                fields=["status", "payment_status"],
                name="core_jobcar_status_a71856_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="jobcard",
            index=models.Index(
                fields=["schedule_date", "status"],
                name="core_jobcar_schedul_a93e98_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="jobcard",
            index=models.Index(
                fields=["client", "status"], name="core_jobcar_client__b678c7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobcard",
            index=models.Index(
                fields=["technician_name", "schedule_date"],
                name="core_jobcar_technic_0d971c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="renewal",
            index=models.Index(
                fields=["due_date", "status"], name="core_renewa_due_dat_57b48f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="renewal",
            index=models.Index(
                fields=["jobcard", "status"], name="core_renewa_jobcard_c55239_idx"
            ),
        ),
    ]
