# Generated by Django 4.2.23 on 2025-08-21 18:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_client_options_alter_inquiry_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inquiry",
            name="is_read",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name="inquiry",
            index=models.Index(
                fields=["is_read", "status"], name="core_inquir_is_read_7faeca_idx"
            ),
        ),
    ]
