# Generated by Django 4.2.23 on 2025-09-07 14:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_inquiry_is_read_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobcard",
            name="contract_duration",
            field=models.CharField(
                blank=True,
                choices=[("12", "12 Months"), ("6", "6 Months"), ("3", "3 Months")],
                db_index=True,
                max_length=2,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="jobcard",
            name="job_type",
            field=models.CharField(
                choices=[("Customer", "Customer"), ("Society", "Society")],
                db_index=True,
                default="Customer",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="jobcard",
            index=models.Index(
                fields=["job_type", "status"], name="core_jobcar_job_typ_0d83da_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobcard",
            index=models.Index(
                fields=["contract_duration", "job_type"],
                name="core_jobcar_contrac_86b78b_idx",
            ),
        ),
    ]
