# Generated by Django 4.2.23 on 2025-09-07 15:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_jobcard_contract_duration_jobcard_job_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobcard",
            name="is_paused",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
