# Generated by Django 4.2.23 on 2025-09-07 16:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_jobcard_is_paused"),
    ]

    operations = [
        migrations.AddField(
            model_name="renewal",
            name="renewal_type",
            field=models.CharField(
                choices=[
                    ("Contract", "Contract Renewal"),
                    ("Monthly", "Monthly Reminder"),
                ],
                db_index=True,
                default="Contract",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="renewal",
            name="urgency_level",
            field=models.CharField(
                choices=[("High", "High"), ("Medium", "Medium"), ("Normal", "Normal")],
                db_index=True,
                default="Normal",
                max_length=10,
            ),
        ),
        migrations.AddIndex(
            model_name="renewal",
            index=models.Index(
                fields=["renewal_type", "status"], name="core_renewa_renewal_1a2a2c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="renewal",
            index=models.Index(
                fields=["urgency_level", "due_date"],
                name="core_renewa_urgency_3ec816_idx",
            ),
        ),
    ]
