# Generated by Django 4.2.23 on 2025-09-07 18:29

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_renewal_renewal_type_renewal_urgency_level_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobcard",
            name="grand_total",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=15,
                validators=[core.validators.validate_non_negative_decimal],
            ),
        ),
        migrations.AlterField(
            model_name="jobcard",
            name="price_subtotal",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=15,
                validators=[core.validators.validate_non_negative_decimal],
            ),
        ),
    ]
