# Generated by Django 4.2.23 on 2025-09-08 06:49

import core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_update_price_validators"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="address",
            field=models.TextField(
                blank=True,
                help_text="Complete address of the client (optional)",
                null=True,
                verbose_name="Address",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="city",
            field=models.CharField(
                db_index=True,
                help_text="City where the client is located",
                max_length=100,
                verbose_name="City",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                help_text="Date and time when the record was created",
                verbose_name="Created At",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="email",
            field=models.EmailField(
                blank=True,
                db_index=True,
                help_text="Client's email address (optional)",
                max_length=254,
                null=True,
                verbose_name="Email Address",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="full_name",
            field=models.CharField(
                db_index=True,
                help_text="Complete name of the client",
                max_length=255,
                verbose_name="Full Name",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="is_active",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Whether the client is currently active",
                verbose_name="Is Active",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="mobile",
            field=models.CharField(
                db_index=True,
                help_text="10-digit mobile number (must be unique)",
                max_length=10,
                unique=True,
                validators=[core.validators.validate_mobile_number],
                verbose_name="Mobile Number",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="notes",
            field=models.TextField(
                blank=True,
                help_text="Additional notes about the client (optional)",
                null=True,
                verbose_name="Notes",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                db_index=True,
                help_text="Date and time when the record was last updated",
                verbose_name="Updated At",
            ),
        ),
        migrations.AlterField(
            model_name="inquiry",
            name="city",
            field=models.CharField(
                db_index=True,
                help_text="City where the service is required",
                max_length=100,
                verbose_name="City",
            ),
        ),
        migrations.AlterField(
            model_name="inquiry",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                help_text="Date and time when the record was created",
                verbose_name="Created At",
            ),
        ),
        migrations.AlterField(
            model_name="inquiry",
            name="email",
            field=models.EmailField(
                blank=True,
                db_index=True,
                help_text="Email address of the inquirer (optional)",
                max_length=254,
                null=True,
                verbose_name="Email Address",
            ),
        ),
        migrations.AlterField(
            model_name="inquiry",
            name="is_read",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Whether the inquiry has been read by staff",
                verbose_name="Is Read",
            ),
        ),
        migrations.AlterField(
            model_name="inquiry",
            name="message",
            field=models.TextField(
                help_text="Detailed message or inquiry from the customer",
                verbose_name="Message",
            ),
        ),
        migrations.AlterField(
            model_name="inquiry",
            name="mobile",
            field=models.CharField(
                db_index=True,
                help_text="10-digit mobile number of the inquirer",
                max_length=10,
                validators=[core.validators.validate_mobile_number],
                verbose_name="Mobile Number",
            ),
        ),
        migrations.AlterField(
            model_name="inquiry",
            name="name",
            field=models.CharField(
                db_index=True,
                help_text="Name of the person making the inquiry",
                max_length=255,
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="inquiry",
            name="service_interest",
            field=models.CharField(
                db_index=True,
                help_text="Type of pest control service the customer is interested in",
                max_length=255,
                verbose_name="Service Interest",
            ),
        ),
        migrations.AlterField(
            model_name="inquiry",
            name="status",
            field=models.CharField(
                choices=[
                    ("New", "New"),
                    ("Contacted", "Contacted"),
                    ("Converted", "Converted"),
                    ("Closed", "Closed"),
                ],
                db_index=True,
                default="New",
                help_text="Current status of the inquiry",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="inquiry",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                db_index=True,
                help_text="Date and time when the record was last updated",
                verbose_name="Updated At",
            ),
        ),
        migrations.AlterField(
            model_name="jobcard",
            name="client",
            field=models.ForeignKey(
                help_text="Client for whom this job card is created",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jobcards",
                to="core.client",
                verbose_name="Client",
            ),
        ),
        migrations.AlterField(
            model_name="jobcard",
            name="code",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Unique identifier for the job card (auto-generated)",
                max_length=20,
                unique=True,
                validators=[core.validators.validate_job_code],
                verbose_name="Job Code",
            ),
        ),
        migrations.AlterField(
            model_name="jobcard",
            name="contract_duration",
            field=models.CharField(
                blank=True,
                choices=[("12", "12 Months"), ("6", "6 Months"), ("3", "3 Months")],
                db_index=True,
                help_text="Duration of the service contract in months",
                max_length=2,
                null=True,
                verbose_name="Contract Duration",
            ),
        ),
        migrations.AlterField(
            model_name="jobcard",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                help_text="Date and time when the record was created",
                verbose_name="Created At",
            ),
        ),
        migrations.AlterField(
            model_name="jobcard",
            name="grand_total",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Total amount including tax (auto-calculated)",
                max_digits=15,
                validators=[core.validators.validate_non_negative_decimal],
                verbose_name="Grand Total",
            ),
        ),
        migrations.AlterField(
            model_name="jobcard",
            name="is_paused",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Whether the job is currently paused",
                verbose_name="Is Paused",
            ),
        ),
        migrations.AlterField(
            model_name="jobcard",
            name="job_type",
            field=models.CharField(
                choices=[("Customer", "Customer"), ("Society", "Society")],
                db_index=True,
                default="Customer",
                help_text="Type of job - Customer or Society",
                max_length=20,
                verbose_name="Job Type",
            ),
        ),
        migrations.AlterField(
            model_name="jobcard",
            name="next_service_date",
            field=models.DateField(
                blank=True,
                db_index=True,
                help_text="Date for the next scheduled service (optional)",
                null=True,
                verbose_name="Next Service Date",
            ),
        ),
        migrations.AlterField(
            model_name="jobcard",
            name="notes",
            field=models.TextField(
                blank=True,
                help_text="Additional notes about the job (optional)",
                null=True,
                verbose_name="Notes",
            ),
        ),
        migrations.AlterField(
            model_name="jobcard",
            name="payment_status",
            field=models.CharField(
                choices=[("Unpaid", "Unpaid"), ("Paid", "Paid")],
                db_index=True,
                default="Unpaid",
                help_text="Current payment status of the job",
                max_length=20,
                verbose_name="Payment Status",
            ),
        ),
        migrations.AlterField(
            model_name="jobcard",
            name="price_subtotal",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Subtotal amount before tax",
                max_digits=15,
                validators=[core.validators.validate_non_negative_decimal],
                verbose_name="Price Subtotal",
            ),
        ),
        migrations.AlterField(
            model_name="jobcard",
            name="schedule_date",
            field=models.DateField(
                db_index=True,
                help_text="Date when the service is scheduled",
                verbose_name="Schedule Date",
            ),
        ),
        migrations.AlterField(
            model_name="jobcard",
            name="service_type",
            field=models.CharField(
                db_index=True,
                help_text="Type of pest control service to be provided",
                max_length=255,
                verbose_name="Service Type",
            ),
        ),
        migrations.AlterField(
            model_name="jobcard",
            name="status",
            field=models.CharField(
                choices=[
                    ("Enquiry", "Enquiry"),
                    ("WIP", "WIP"),
                    ("Done", "Done"),
                    ("Hold", "Hold"),
                    ("Cancel", "Cancel"),
                    ("Inactive", "Inactive"),
                ],
                db_index=True,
                default="Enquiry",
                help_text="Current status of the job card",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="jobcard",
            name="tax_percent",
            field=models.PositiveIntegerField(
                default=18,
                help_text="Tax percentage to be applied (default: 18%)",
                validators=[core.validators.validate_tax_percent],
                verbose_name="Tax Percentage",
            ),
        ),
        migrations.AlterField(
            model_name="jobcard",
            name="technician_name",
            field=models.CharField(
                db_index=True,
                help_text="Name of the technician assigned to this job",
                max_length=255,
                verbose_name="Technician Name",
            ),
        ),
        migrations.AlterField(
            model_name="jobcard",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                db_index=True,
                help_text="Date and time when the record was last updated",
                verbose_name="Updated At",
            ),
        ),
        migrations.AlterField(
            model_name="renewal",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                help_text="Date and time when the record was created",
                verbose_name="Created At",
            ),
        ),
        migrations.AlterField(
            model_name="renewal",
            name="due_date",
            field=models.DateTimeField(
                db_index=True,
                default=django.utils.timezone.now,
                help_text="Date and time when the renewal is due",
                verbose_name="Due Date",
            ),
        ),
        migrations.AlterField(
            model_name="renewal",
            name="jobcard",
            field=models.ForeignKey(
                help_text="Job card associated with this renewal",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="renewals",
                to="core.jobcard",
                verbose_name="Job Card",
            ),
        ),
        migrations.AlterField(
            model_name="renewal",
            name="remarks",
            field=models.TextField(
                blank=True,
                help_text="Additional remarks about the renewal (optional)",
                null=True,
                verbose_name="Remarks",
            ),
        ),
        migrations.AlterField(
            model_name="renewal",
            name="renewal_type",
            field=models.CharField(
                choices=[
                    ("Contract", "Contract Renewal"),
                    ("Monthly", "Monthly Reminder"),
                ],
                db_index=True,
                default="Contract",
                help_text="Type of renewal - Contract or Monthly reminder",
                max_length=20,
                verbose_name="Renewal Type",
            ),
        ),
        migrations.AlterField(
            model_name="renewal",
            name="status",
            field=models.CharField(
                choices=[("Due", "Due"), ("Completed", "Completed")],
                db_index=True,
                default="Due",
                help_text="Current status of the renewal",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="renewal",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                db_index=True,
                help_text="Date and time when the record was last updated",
                verbose_name="Updated At",
            ),
        ),
        migrations.AlterField(
            model_name="renewal",
            name="urgency_level",
            field=models.CharField(
                choices=[("High", "High"), ("Medium", "Medium"), ("Normal", "Normal")],
                db_index=True,
                default="Normal",
                help_text="Priority level based on due date proximity",
                max_length=10,
                verbose_name="Urgency Level",
            ),
        ),
    ]
