# Generated by Django 4.2.23 on 2025-09-11 17:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_alter_client_address_alter_client_city_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobcard",
            name="reference",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Source of reference for this job card",
                max_length=50,
                null=True,
                verbose_name="Reference",
            ),
        ),
    ]
