# Generated by Django 4.2.23 on 2025-09-15 09:48

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_jobcard_reference"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobcard",
            name="grand_total",
            field=models.DecimalField(
                decimal_places=6,
                default=0,
                help_text="Total amount including tax (auto-calculated)",
                max_digits=15,
                validators=[core.validators.validate_non_negative_decimal],
                verbose_name="Grand Total",
            ),
        ),
        migrations.AlterField(
            model_name="jobcard",
            name="price_subtotal",
            field=models.DecimalField(
                decimal_places=6,
                help_text="Subtotal amount before tax",
                max_digits=15,
                validators=[core.validators.validate_non_negative_decimal],
                verbose_name="Price Subtotal",
            ),
        ),
    ]
