# Generated by Django 4.2.23 on 2025-09-15 09:50

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_alter_jobcard_grand_total_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobcard",
            name="grand_total",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                help_text="Total amount including tax (auto-calculated)",
                max_digits=10,
                validators=[core.validators.validate_non_negative_decimal],
                verbose_name="Grand Total",
            ),
        ),
    ]
