# Generated by Django 4.2.23 on 2025-09-15 10:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_alter_jobcard_grand_total"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobcard",
            name="grand_total",
        ),
        migrations.RemoveField(
            model_name="jobcard",
            name="price_subtotal",
        ),
        migrations.RemoveField(
            model_name="jobcard",
            name="tax_percent",
        ),
        migrations.AddField(
            model_name="jobcard",
            name="price",
            field=models.CharField(
                default="",
                help_text="Service price as entered by user",
                max_length=50,
                verbose_name="Service Price",
            ),
        ),
    ]
