# Generated by Django 4.2.23 on 2025-09-22 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_devicetoken_notificationsubscription_notificationlog_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='notificationsubscription',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='notificationsubscription',
            name='device_token',
        ),
        migrations.RemoveIndex(
            model_name='devicetoken',
            name='core_device_device__6f3ba9_idx',
        ),
        migrations.RemoveIndex(
            model_name='devicetoken',
            name='core_device_is_acti_dd8d21_idx',
        ),
        migrations.RemoveIndex(
            model_name='notificationlog',
            name='core_notifi_status_61f798_idx',
        ),
        migrations.RemoveIndex(
            model_name='notificationlog',
            name='core_notifi_topic_ef61b8_idx',
        ),
        migrations.RemoveIndex(
            model_name='notificationlog',
            name='core_notifi_created_10764e_idx',
        ),
        migrations.RemoveField(
            model_name='devicetoken',
            name='device_type',
        ),
        migrations.RemoveField(
            model_name='devicetoken',
            name='last_used',
        ),
        migrations.RemoveField(
            model_name='devicetoken',
            name='user_agent',
        ),
        migrations.RemoveField(
            model_name='notificationlog',
            name='data_payload',
        ),
        migrations.RemoveField(
            model_name='notificationlog',
            name='failure_count',
        ),
        migrations.RemoveField(
            model_name='notificationlog',
            name='firebase_message_id',
        ),
        migrations.RemoveField(
            model_name='notificationlog',
            name='notification_type',
        ),
        migrations.RemoveField(
            model_name='notificationlog',
            name='success_count',
        ),
        migrations.RemoveField(
            model_name='notificationlog',
            name='target_tokens',
        ),
        migrations.RemoveField(
            model_name='notificationlog',
            name='topic',
        ),
        migrations.AddField(
            model_name='devicetoken',
            name='device_name',
            field=models.CharField(blank=True, help_text="Optional name to identify the device (e.g., 'Admin Phone')", max_length=100, null=True, verbose_name='Device Name'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed')], db_index=True, default='sent', help_text='Notification delivery status', max_length=10, verbose_name='Status'),
        ),
        migrations.DeleteModel(
            name='NotificationSubscription',
        ),
    ]
