# Generated by Django 4.2.23 on 2025-10-27 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_increase_device_name_length'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='jobcard',
            name='core_jobcar_technic_0d971c_idx',
        ),
        migrations.RemoveField(
            model_name='jobcard',
            name='technician_name',
        ),
        migrations.AddField(
            model_name='jobcard',
            name='client_address',
            field=models.TextField(blank=True, help_text='Address where the service will be performed', null=True, verbose_name='Client Address'),
        ),
    ]
