# Generated by Django 4.2.23 on 2025-10-27 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_technician_add_client_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='extra_notes',
            field=models.TextField(blank=True, help_text='Additional notes or comments about the job card', null=True, verbose_name='Extra Notes'),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='lead_source',
            field=models.CharField(blank=True, db_index=True, help_text='Source where the lead came from (Website, Facebook, etc.)', max_length=100, null=True, verbose_name='Lead Source'),
        ),
    ]
