# Generated by Django 4.2.23 on 2025-10-27 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_jobcard_extra_notes_jobcard_lead_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcard',
            name='service_type',
            field=models.CharField(db_index=True, help_text='Type of pest control service to be provided', max_length=500, verbose_name='Service Type'),
        ),
    ]
