# Generated by Django 4.2.23 on 2025-11-01 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_jobcard_service_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renewal',
            name='due_date',
            field=models.DateField(db_index=True, help_text='Date when the renewal is due', verbose_name='Due Date'),
        ),
    ]
