# Generated by Django 4.2.7 on 2025-11-02 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_fix_renewal_due_date_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcard',
            name='price',
            field=models.CharField(default='', help_text='Service price as entered by user', max_length=200, verbose_name='Service Price'),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='reference',
            field=models.CharField(blank=True, db_index=True, help_text='Source of reference for this job card', max_length=200, null=True, verbose_name='Reference'),
        ),
    ]
