# Generated by Django 4.2.7 on 2025-11-02 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_jobcard_price_alter_jobcard_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobcard',
            name='lead_source',
        ),
    ]
