# Generated by Django 4.2.7 on 2025-11-02 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_remove_jobcard_lead_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='city',
            field=models.CharField(db_index=True, help_text='City where the client is located', max_length=255, verbose_name='City'),
        ),
    ]
