# Generated by Django 4.2.7 on 2025-11-12 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_backfill_jobcard_client_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeviceToken',
        ),
        migrations.DeleteModel(
            name='NotificationLog',
        ),
    ]
