# Generated by Django 4.2.7 on 2026-04-21 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_delete_devicetoken_delete_notificationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='area',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Area'),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='assigned_to',
            field=models.CharField(blank=True, db_index=True, help_text='Technician or driver assigned to this job', max_length=255, null=True, verbose_name='Assigned Technician'),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='bhk_size',
            field=models.CharField(blank=True, choices=[('1 RK', '1 RK'), ('1 BHK', '1 BHK'), ('2 BHK', '2 BHK'), ('3 BHK', '3 BHK'), ('4 BHK', '4 BHK')], db_index=True, max_length=20, null=True, verbose_name='BHK Size'),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='building_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Building Name'),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='flat_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Flat Number'),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='landmark',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Landmark'),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='property_type',
            field=models.CharField(blank=True, choices=[('Home / Flat', 'Home / Flat'), ('Bungalow', 'Bungalow'), ('Hotel', 'Hotel'), ('Office', 'Office'), ('Commercial Space', 'Commercial Space')], db_index=True, max_length=50, null=True, verbose_name='Property Type'),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='service_category',
            field=models.CharField(choices=[('One-Time Service', 'One-Time Service'), ('AMC', 'AMC (Annual Maintenance Contract)')], db_index=True, default='One-Time Service', help_text='One-Time Service or AMC', max_length=50, verbose_name='Service Category'),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='time_slot',
            field=models.CharField(blank=True, choices=[('10am–12pm', '10am–12pm'), ('12pm–2pm', '12pm–2pm'), ('2pm–4pm', '2pm–4pm'), ('4pm–6pm', '4pm–6pm')], db_index=True, max_length=50, null=True, verbose_name='Time Slot'),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Hold', 'Hold'), ('Inactive', 'Inactive')], db_index=True, default='Pending', help_text='Current status of the job card', max_length=20, verbose_name='Status'),
        ),
    ]
