# Generated by Django 4.2.7 on 2026-04-21 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_jobcard_area_jobcard_assigned_to_jobcard_bhk_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='area',
            field=models.CharField(blank=True, help_text='Area or locality', max_length=255, null=True, verbose_name='Area'),
        ),
        migrations.AddField(
            model_name='client',
            name='building_name',
            field=models.CharField(blank=True, help_text='Name of the building or society', max_length=255, null=True, verbose_name='Building/Society Name'),
        ),
        migrations.AddField(
            model_name='client',
            name='flat_number',
            field=models.CharField(blank=True, help_text='Flat/Shop/Office number', max_length=100, null=True, verbose_name='Flat Number'),
        ),
        migrations.AddField(
            model_name='client',
            name='landmark',
            field=models.CharField(blank=True, help_text='Nearby landmark for easier location', max_length=255, null=True, verbose_name='Landmark'),
        ),
    ]
