# Generated by Django 4.2.7 on 2026-04-21 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_client_area_client_building_name_client_flat_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='area',
            field=models.CharField(blank=True, help_text='Area or locality', max_length=255, null=True, verbose_name='Area'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='building_name',
            field=models.CharField(blank=True, help_text='Name of the building or society', max_length=255, null=True, verbose_name='Building Name'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='flat_number',
            field=models.CharField(blank=True, help_text='Flat, apartment, or shop number', max_length=255, null=True, verbose_name='Flat Number'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='landmark',
            field=models.CharField(blank=True, help_text='Nearby landmark', max_length=255, null=True, verbose_name='Landmark'),
        ),
    ]
