# Generated by Django 4.2.7 on 2026-04-24 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_inquiry_area_inquiry_building_name_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='client',
            name='core_client_city_d3dc61_idx',
        ),
        migrations.RemoveIndex(
            model_name='inquiry',
            name='core_inquir_status_1ae09a_idx',
        ),
        migrations.RemoveField(
            model_name='client',
            name='area',
        ),
        migrations.RemoveField(
            model_name='client',
            name='building_name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='flat_number',
        ),
        migrations.RemoveField(
            model_name='client',
            name='landmark',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='area',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='building_name',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='flat_number',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='landmark',
        ),
        migrations.RemoveField(
            model_name='jobcard',
            name='area',
        ),
        migrations.RemoveField(
            model_name='jobcard',
            name='building_name',
        ),
        migrations.RemoveField(
            model_name='jobcard',
            name='flat_number',
        ),
        migrations.RemoveField(
            model_name='jobcard',
            name='landmark',
        ),
        migrations.AddField(
            model_name='client',
            name='state',
            field=models.CharField(blank=True, db_index=True, help_text='State where the client is located', max_length=100, null=True, verbose_name='State'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='state',
            field=models.CharField(blank=True, db_index=True, help_text='State where the service is required', max_length=100, null=True, verbose_name='State'),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='city',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='state',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='State'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['city', 'state', 'is_active'], name='core_client_city_3f7ca8_idx'),
        ),
        migrations.AddIndex(
            model_name='inquiry',
            index=models.Index(fields=['status', 'city', 'state'], name='core_inquir_status_1133c4_idx'),
        ),
    ]
