# Generated by Django 4.2.7 on 2026-04-24 13:51

import core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_remove_client_core_client_city_d3dc61_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Date and time when the record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Date and time when the record was last updated', verbose_name='Updated At')),
                ('name', models.CharField(db_index=True, help_text='Full name of the technician', max_length=255, verbose_name='Name')),
                ('mobile', models.CharField(db_index=True, help_text='10-digit primary mobile number', max_length=10, unique=True, validators=[core.validators.validate_mobile_number], verbose_name='Mobile Number')),
                ('age', models.IntegerField(blank=True, help_text='Age of the technician', null=True, verbose_name='Age')),
                ('alternative_mobile', models.CharField(blank=True, help_text='Secondary contact number', max_length=10, null=True, validators=[core.validators.validate_mobile_number], verbose_name='Alternative Number')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether the technician is currently available', verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Technician',
                'verbose_name_plural': 'Technicians',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='assigned_to',
            field=models.CharField(blank=True, db_index=True, help_text='Technician name string (legacy support)', max_length=255, null=True, verbose_name='Assigned Technician (Legacy)'),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='technician',
            field=models.ForeignKey(blank=True, help_text='Registered technician assigned to this job', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobcards', to='core.technician', verbose_name='Assigned Technician'),
        ),
    ]
