# Generated by Django 4.2.7 on 2026-04-24 14:07

import core.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0030_technician_alter_jobcard_assigned_to_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CRMInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Date and time when the record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Date and time when the record was last updated', verbose_name='Updated At')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('mobile', models.CharField(db_index=True, max_length=10, validators=[core.validators.validate_mobile_number])),
                ('location', models.CharField(blank=True, max_length=500, null=True)),
                ('pest_type', models.CharField(choices=[('Cockroach', 'Cockroach'), ('Ants', 'Ants'), ('Bed Bugs', 'Bed Bugs'), ('Termite', 'Termite'), ('Rodent', 'Rodent'), ('Mosquito', 'Mosquito'), ('Other', 'Other')], default='Other', max_length=50)),
                ('remark', models.TextField(blank=True, null=True)),
                ('inquiry_date', models.DateField(default=django.utils.timezone.now)),
                ('inquiry_time', models.TimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('New', 'New'), ('Contacted', 'Contacted'), ('Converted', 'Converted'), ('Closed', 'Closed')], default='New', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_inquiries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CRM Inquiry',
                'verbose_name_plural': 'CRM Inquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
