# Generated by Django 4.2.7 on 2026-04-25 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_crminquiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcard',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('On Process', 'On Process'), ('Done', 'Done')], db_index=True, default='Pending', help_text='Current status of the job card', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='time_slot',
            field=models.CharField(blank=True, choices=[('8am–10am', '8am–10am'), ('10am–12pm', '10am–12pm'), ('12pm–2pm', '12pm–2pm'), ('2pm–4pm', '2pm–4pm'), ('4pm–6pm', '4pm–6pm'), ('6pm–8pm', '6pm–8pm')], db_index=True, max_length=50, null=True, verbose_name='Time Slot'),
        ),
    ]
