# Generated by Django 4.2.7 on 2026-04-26 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_migrate_job_statuses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crminquiry',
            name='pest_type',
            field=models.CharField(default='Other', max_length=255),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='time_slot',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Time Slot'),
        ),
    ]
