# Generated by Django 4.2.7 on 2026-04-27 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_alter_crminquiry_pest_type_alter_jobcard_time_slot'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='jobcard',
            name='core_jobcar_contrac_86b78b_idx',
        ),
        migrations.AddField(
            model_name='jobcard',
            name='commercial_type',
            field=models.CharField(choices=[('home', 'Home'), ('hotel', 'Hotel'), ('society', 'Society'), ('villa', 'Villa'), ('office', 'Office'), ('other', 'Other')], db_index=True, default='home', help_text='Detailed category of the booking', max_length=20, verbose_name='Commercial Type'),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='is_price_estimated',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether the price is a dynamic estimate (for commercial types)', verbose_name='Is Price Estimated'),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='job_type',
            field=models.CharField(choices=[('Customer', 'Customer'), ('Society', 'Society')], db_index=True, default='Customer', help_text='Type of job - Customer or Society (Legacy)', max_length=20, verbose_name='Job Type'),
        ),
        migrations.AddIndex(
            model_name='jobcard',
            index=models.Index(fields=['commercial_type', 'status'], name='core_jobcar_commerc_36a38d_idx'),
        ),
        migrations.AddIndex(
            model_name='jobcard',
            index=models.Index(fields=['contract_duration', 'commercial_type'], name='core_jobcar_contrac_097418_idx'),
        ),
    ]
