# Generated by Django 4.2.7 on 2026-04-28 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_remove_jobcard_core_jobcar_contrac_86b78b_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='max_cycle',
            field=models.IntegerField(default=1, help_text='Total number of services in the contract', verbose_name='Max Cycle'),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='parent_job',
            field=models.ForeignKey(blank=True, help_text='The previous job in the service sequence', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_up_jobs', to='core.jobcard', verbose_name='Parent Job'),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='service_cycle',
            field=models.IntegerField(default=1, help_text='Current service number in the sequence', verbose_name='Service Cycle'),
        ),
    ]
