# Generated by Django 4.2.7 on 2026-04-28 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_jobcard_max_cycle_jobcard_parent_job_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcard',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('On Process', 'On Process'), ('Done', 'Done'), ('Cancelled', 'Cancelled')], db_index=True, default='Pending', help_text='Current status of the job card', max_length=20, verbose_name='Status'),
        ),
    ]
