# Generated by Django 4.2.7 on 2026-04-29 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_alter_jobcard_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='cancellation_reason',
            field=models.TextField(blank=True, help_text='Reason why the booking was cancelled', null=True, verbose_name='Cancellation Reason'),
        ),
    ]
