# Generated by Django 4.2.7 on 2026-04-29 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_jobcard_cancellation_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='removal_remarks',
            field=models.TextField(blank=True, help_text='Remarks when a technician is removed from an On Process job', null=True, verbose_name='Removal Remarks'),
        ),
    ]
