# Generated by Django 4.2.7 on 2026-04-29 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_jobcard_removal_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='technician',
            name='city',
            field=models.CharField(blank=True, db_index=True, help_text='City where the technician is based', max_length=100, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='technician',
            name='last_active',
            field=models.DateTimeField(blank=True, help_text='Last known timestamp of activity', null=True, verbose_name='Last Active'),
        ),
        migrations.AddField(
            model_name='technician',
            name='service_area',
            field=models.CharField(blank=True, db_index=True, help_text='Primary area where the technician operates', max_length=255, null=True, verbose_name='Service Area'),
        ),
    ]
