# Generated by Django 4.2.7 on 2026-04-30 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_technician_city_technician_last_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Accepted At'),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Completed At'),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='is_accepted',
            field=models.BooleanField(default=False, verbose_name='Is Accepted'),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Started At'),
        ),
    ]
