# Generated by Django 4.2.7 on 2026-04-30 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_jobcard_accepted_at_jobcard_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='is_service_call',
            field=models.BooleanField(default=False, verbose_name='Is Service Call'),
        ),
    ]
