# Generated by Django 4.2.7 on 2026-05-05 09:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_jobcard_is_service_call'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='jobcard',
            name='core_jobcar_schedul_a93e98_idx',
        ),
        migrations.RenameField(
            model_name='jobcard',
            old_name='schedule_date',
            new_name='schedule_datetime',
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='schedule_datetime',
            field=models.DateTimeField(db_index=True, help_text='Date and time when the service is scheduled', verbose_name='Schedule DateTime'),
        ),
        migrations.AddIndex(
            model_name='jobcard',
            index=models.Index(fields=['schedule_datetime', 'status'], name='core_jobcar_schedul_719406_idx'),
        ),
    ]
