# Generated by Django 4.2.7 on 2026-05-05 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_remove_jobcard_core_jobcar_schedul_a93e98_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crminquiry',
            name='is_reminder_done',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Is Reminder Done'),
        ),
        migrations.AddField(
            model_name='crminquiry',
            name='reminder_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Reminder Date'),
        ),
        migrations.AddField(
            model_name='crminquiry',
            name='reminder_note',
            field=models.TextField(blank=True, null=True, verbose_name='Reminder Note'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='is_reminder_done',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Is Reminder Done'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='reminder_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Reminder Date'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='reminder_note',
            field=models.TextField(blank=True, null=True, verbose_name='Reminder Note'),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Is Read'),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='is_reminder_done',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Is Reminder Done'),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='reminder_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Reminder Date'),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='reminder_note',
            field=models.TextField(blank=True, null=True, verbose_name='Reminder Note'),
        ),
        migrations.AlterField(
            model_name='crminquiry',
            name='remark',
            field=models.TextField(blank=True, null=True, verbose_name='Remark'),
        ),
    ]
