# Generated by Django 4.2.7 on 2026-05-07 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='crminquiry',
            name='reminder_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Reminder Time'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='reminder_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Reminder Time'),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='reminder_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Reminder Time'),
        ),
        migrations.AlterField(
            model_name='client',
            name='city',
            field=models.CharField(blank=True, db_index=True, help_text='City where the client is located', max_length=255, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='schedule_datetime',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Date and time when the service is scheduled', null=True, verbose_name='Schedule DateTime'),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='service_type',
            field=models.CharField(blank=True, db_index=True, help_text='Type of pest control service to be provided', max_length=500, null=True, verbose_name='Service Type'),
        ),
    ]
