# Generated by Django 4.2.7 on 2026-05-08 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_crminquiry_reminder_time_inquiry_reminder_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcard',
            name='price',
            field=models.CharField(blank=True, default='', help_text='Service price as entered by user', max_length=200, verbose_name='Service Price'),
        ),
    ]
