# Generated by Django 4.2.7 on 2026-05-09 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_alter_jobcard_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='complaint_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='complaint_parent_booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='core.jobcard', verbose_name='Parent Booking for Complaint'),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='complaint_status',
            field=models.CharField(choices=[('Open', 'Open'), ('Assigned', 'Assigned'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved'), ('Closed', 'Closed')], db_index=True, default='Open', max_length=50),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='complaint_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='is_complaint_call',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], db_index=True, default='Medium', max_length=20),
        ),
    ]
