# Generated by Django 4.2.7 on 2026-05-09 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='payment_mode',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Online', 'Online')], db_index=True, max_length=20, null=True, verbose_name='Payment Mode'),
        ),
    ]
