# Generated by Django 4.2.7 on 2026-05-10 15:31

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_jobcard_payment_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='estimated_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The price calculated by the website', max_digits=10, null=True, validators=[core.validators.validate_non_negative_decimal], verbose_name='Estimated Price'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='is_inspection_required',
            field=models.BooleanField(db_index=True, default=False, help_text='Flag for cases where price is not fixed', verbose_name='Is Inspection Required'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='pest_problems',
            field=models.TextField(blank=True, help_text='List of pests selected by the user', null=True, verbose_name='Pest Problems'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='premise_size',
            field=models.CharField(blank=True, db_index=True, help_text='Specific size for residential quotes (e.g., 1bhk, 2bhk)', max_length=50, null=True, verbose_name='Premise Size'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='premise_type',
            field=models.CharField(blank=True, db_index=True, help_text='Categorizes the property type (e.g., residential, commercial)', max_length=50, null=True, verbose_name='Premise Type'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='service_frequency',
            field=models.CharField(blank=True, db_index=True, help_text='Whether user wants a one-time treatment or AMC', max_length=50, null=True, verbose_name='Service Frequency'),
        ),
    ]
