# Generated by Django 4.2.7 on 2026-05-12 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0052_crminquiry_service_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='crminquiry',
            name='converted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_crm_inquiries', to=settings.AUTH_USER_MODEL, verbose_name='Converted By'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='converted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_inquiries', to=settings.AUTH_USER_MODEL, verbose_name='Converted By'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_inquiries', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bookings', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='done_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='done_bookings', to=settings.AUTH_USER_MODEL, verbose_name='Done By'),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='on_process_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='on_process_bookings', to=settings.AUTH_USER_MODEL, verbose_name='On Process By'),
        ),
        migrations.AddField(
            model_name='renewal',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_renewals', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
    ]
