# Generated by Django 4.2.7 on 2026-05-12 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_crminquiry_converted_by_inquiry_converted_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcard',
            name='reference',
            field=models.CharField(db_index=True, default='Other', help_text='Source of reference for this job card', max_length=200, verbose_name='Reference'),
        ),
    ]
