# Generated by Django 4.2.7 on 2026-05-12 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_alter_jobcard_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='remark',
            field=models.TextField(blank=True, null=True, verbose_name='Remark'),
        ),
    ]
