# Generated by Django 4.2.7 on 2026-05-12 14:11

import core.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0055_inquiry_remark'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Date and time when the record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Date and time when the record was last updated', verbose_name='Updated At')),
                ('inquiry_type', models.CharField(choices=[('crm', 'CRM Inquiry'), ('website', 'Website Inquiry')], db_index=True, max_length=20, verbose_name='Inquiry Type')),
                ('inquiry_id', models.IntegerField(db_index=True, verbose_name='Inquiry ID')),
                ('customer_name', models.CharField(max_length=255, verbose_name='Customer Name')),
                ('mobile_number', models.CharField(max_length=10, validators=[core.validators.validate_mobile_number], verbose_name='Mobile Number')),
                ('reminder_date', models.DateField(db_index=True, verbose_name='Reminder Date')),
                ('reminder_time', models.TimeField(blank=True, null=True, verbose_name='Reminder Time')),
                ('note', models.TextField(verbose_name='Note')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], db_index=True, default='pending', max_length=20, verbose_name='Status')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reminders', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Reminder',
                'verbose_name_plural': 'Reminders',
                'ordering': ['reminder_date', 'reminder_time'],
            },
        ),
    ]
