# Generated by Django 4.2.7 on 2026-05-13 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_reminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Is Read'),
        ),
    ]
