# Generated by Django 4.2.7 on 2026-05-13 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_feedback_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='included_in_amc',
            field=models.BooleanField(db_index=True, default=False, help_text='True if this service is free/included in a previously paid AMC', verbose_name='Included in AMC'),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='is_amc_main_booking',
            field=models.BooleanField(db_index=True, default=False, help_text='True if this is the first/paid booking of an AMC package', verbose_name='Is AMC Main Booking'),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='is_followup_visit',
            field=models.BooleanField(db_index=True, default=False, help_text='True if this is a follow-up service (AMC or BedBug)', verbose_name='Is Follow-up Visit'),
        ),
    ]
