# Generated by Django 4.2.7 on 2026-05-13 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0001_initial'),
        ('core', '0059_city_country_jobcard_booking_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='partner',
            field=models.ForeignKey(blank=True, help_text='Partner App technician assigned to this booking', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_jobs', to='partner.partner', verbose_name='Assigned Partner'),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='partner_status',
            field=models.CharField(choices=[('pending', 'Pending (Not yet accepted)'), ('accepted', 'Accepted'), ('in_service', 'Service Started'), ('completed', 'Service Completed'), ('rejected', 'Rejected by Technician')], db_index=True, default='pending', help_text='Status in the Technician Partner App workflow', max_length=20, verbose_name='Partner App Status'),
        ),
    ]
