# Generated by Django 4.2.7 on 2026-05-14 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_quotation_quotationscope_quotationpaymentterm_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='location',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='location',
            name='normalized_name',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
    ]
