# Generated by Django 4.2.7 on 2026-05-14 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_alter_location_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('city', 'normalized_name')},
        ),
    ]
