# Generated by Django 4.2.7 on 2026-05-14 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_alter_location_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='master_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.city', verbose_name='City (Master)'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='master_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.country', verbose_name='Country (Master)'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='master_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.location', verbose_name='Location (Master)'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='master_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.state', verbose_name='State (Master)'),
        ),
    ]
