# Generated by Django 4.2.7 on 2026-05-14 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_crminquiry_master_city_crminquiry_master_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crminquiry',
            name='email',
            field=models.EmailField(blank=True, db_index=True, help_text='Email address of the inquirer', max_length=254, null=True, verbose_name='Email Address'),
        ),
    ]
