# Generated by Django 4.2.7 on 2026-05-15 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_crminquiry_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='creation_source',
            field=models.CharField(choices=[('manual', 'Manual'), ('amc_auto', 'AMC Auto'), ('reminder_auto', 'Reminder Auto'), ('complaint_auto', 'Complaint Auto'), ('system', 'System'), ('migration', 'Migration'), ('api', 'API')], db_index=True, default='manual', help_text='Where this booking was created from', max_length=50, verbose_name='Creation Source'),
        ),
    ]
