# Generated by Django 4.2.7 on 2026-05-15 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_jobcard_creation_source'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='jobcard',
            constraint=models.UniqueConstraint(condition=models.Q(('parent_job__isnull', False)), fields=('parent_job', 'service_cycle'), name='unique_amc_cycle_per_parent'),
        ),
    ]
