"""
URL configuration for backend project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/5.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include
from django.http import HttpResponse, JsonResponse
from rest_framework_simplejwt.views import (
    TokenRefreshView,
    TokenVerifyView,
)
from core.auth import CustomTokenObtainPairView
from .api_views import api_docs_view

def health(request):
    return JsonResponse({
        "status": "ok", 
        "service": "pestcontrol-backend", 
        "version": "1.0.0",
        "endpoint": "main"
    })

def root(request):
    return HttpResponse("PestControl Backend API v1.0.0 - Status: Running", content_type="text/plain")


urlpatterns = [
    path('', root, name='root'),  # Root path for Railway healthcheck
    path('health/', health, name='health'),
    path('api-docs/', api_docs_view, name='api_docs'),  # All APIs in one page
    path('admin/', admin.site.urls),
    
    # Authentication endpoints
    path('api/token/', CustomTokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/token/verify/', TokenVerifyView.as_view(), name='token_verify'),
    
    # API documentation - Schema endpoint disabled due to Python 3.13 compatibility
    # path('schema/', get_schema_view(
    #     title="PestControl99 API",
    #     description="Lightweight API schema generated by DRF",
    #     version="1.0.0"
    # ), name='schema'),
    
    # API endpoints
    path('api/', include('core.urls')),
]
