# Generated by Django 4.2.7 on 2026-05-16 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='schema_type',
            field=models.CharField(choices=[('Article', 'Article'), ('BlogPosting', 'Blog Posting'), ('NewsArticle', 'News Article'), ('FAQPage', 'FAQ Page'), ('HowTo', 'How To'), ('Service', 'Service'), ('LocalBusiness', 'Local Business'), ('Organization', 'Organization'), ('WebPage', 'Web Page'), ('BreadcrumbList', 'Breadcrumb List'), ('Review', 'Review'), ('Product', 'Product'), ('QAPage', 'QA Page'), ('VideoObject', 'Video Object'), ('ImageObject', 'Image Object')], default='Article', max_length=50),
        ),
    ]
