import os
import uuid
from django.db import models
from django.utils import timezone
from django.utils.text import slugify
from django.contrib.auth import get_user_model
from django.core.validators import FileExtensionValidator

User = get_user_model()


class BaseModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True, db_index=True)
    updated_at = models.DateTimeField(auto_now=True, db_index=True)

    class Meta:
        abstract = True
        ordering = ["-created_at"]


def blog_image_upload_path(instance, filename):
    ext = "webp"
    unique_name = f"{uuid.uuid4().hex}.{ext}"
    return os.path.join("blog", "images", str(timezone.now().year), str(timezone.now().month), unique_name)


def blog_thumbnail_upload_path(instance, filename):
    ext = "webp"
    unique_name = f"{uuid.uuid4().hex}_thumb.{ext}"
    return os.path.join("blog", "images", str(timezone.now().year), str(timezone.now().month), unique_name)


def blog_medium_upload_path(instance, filename):
    ext = "webp"
    unique_name = f"{uuid.uuid4().hex}_medium.{ext}"
    return os.path.join("blog", "images", str(timezone.now().year), str(timezone.now().month), unique_name)


class Category(BaseModel):
    name = models.CharField(max_length=200, unique=True, db_index=True)
    slug = models.SlugField(max_length=220, unique=True, db_index=True, blank=True)
    description = models.TextField(blank=True)
    meta_title = models.CharField(max_length=160, blank=True)
    meta_description = models.CharField(max_length=320, blank=True)
    is_active = models.BooleanField(default=True, db_index=True)

    class Meta:
        verbose_name = "Category"
        verbose_name_plural = "Categories"
        ordering = ["name"]

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = self._generate_unique_slug()
        super().save(*args, **kwargs)

    def _generate_unique_slug(self):
        base_slug = slugify(self.name)
        slug = base_slug
        counter = 1
        while Category.objects.filter(slug=slug).exclude(pk=self.pk).exists():
            slug = f"{base_slug}-{counter}"
            counter += 1
        return slug


class Tag(BaseModel):
    name = models.CharField(max_length=500, unique=True, db_index=True)
    slug = models.SlugField(max_length=520, unique=True, db_index=True, blank=True)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = self._generate_unique_slug()
        super().save(*args, **kwargs)

    def _generate_unique_slug(self):
        base_slug = slugify(self.name)
        slug = base_slug
        counter = 1
        while Tag.objects.filter(slug=slug).exclude(pk=self.pk).exists():
            slug = f"{base_slug}-{counter}"
            counter += 1
        return slug


class BlogStatus(models.TextChoices):
    DRAFT = "draft", "Draft"
    PUBLISHED = "published", "Published"


class SchemaType(models.TextChoices):
    ARTICLE = "Article", "Article"
    BLOG_POSTING = "BlogPosting", "Blog Posting"
    NEWS_ARTICLE = "NewsArticle", "News Article"
    FAQ_PAGE = "FAQPage", "FAQ Page"
    HOW_TO = "HowTo", "How To"
    SERVICE = "Service", "Service"
    LOCAL_BUSINESS = "LocalBusiness", "Local Business"
    ORGANIZATION = "Organization", "Organization"
    WEB_PAGE = "WebPage", "Web Page"
    BREADCRUMB_LIST = "BreadcrumbList", "Breadcrumb List"
    REVIEW = "Review", "Review"
    PRODUCT = "Product", "Product"
    QA_PAGE = "QAPage", "QA Page"
    VIDEO_OBJECT = "VideoObject", "Video Object"
    IMAGE_OBJECT = "ImageObject", "Image Object"


class Blog(BaseModel):
    # Basic fields
    title = models.CharField(max_length=500, db_index=True)
    slug = models.SlugField(max_length=520, unique=True, db_index=True, blank=True)
    content = models.TextField()
    excerpt = models.TextField(blank=True)

    # Featured image (original full-size, stored as webp)
    featured_image = models.ImageField(
        upload_to=blog_image_upload_path,
        blank=True,
        null=True,
        validators=[FileExtensionValidator(allowed_extensions=["jpg", "jpeg", "png", "webp", "gif"])],
    )
    featured_image_alt = models.CharField(max_length=300, blank=True)
    featured_image_title = models.CharField(max_length=300, blank=True)

    # Responsive image variants (auto-generated by signal)
    image_thumbnail = models.ImageField(upload_to=blog_thumbnail_upload_path, blank=True, null=True)
    image_medium = models.ImageField(upload_to=blog_medium_upload_path, blank=True, null=True)

    # SEO fields
    meta_title = models.CharField(max_length=160, blank=True)
    meta_description = models.CharField(max_length=320, blank=True)
    target_keywords = models.TextField(
        blank=True,
        help_text="Comma-separated target keywords for SEO"
    )
    canonical_url = models.URLField(max_length=500, blank=True)
    schema_type = models.CharField(
        max_length=50,
        choices=SchemaType.choices,
        default=SchemaType.ARTICLE,
    )

    # Open Graph / Social
    og_title = models.CharField(max_length=200, blank=True)
    og_description = models.CharField(max_length=400, blank=True)

    # Status
    status = models.CharField(
        max_length=20,
        choices=BlogStatus.choices,
        default=BlogStatus.DRAFT,
        db_index=True,
    )
    publish_date = models.DateTimeField(null=True, blank=True, db_index=True)

    # Relations
    author = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="blog_posts",
        db_index=True,
    )
    category = models.ForeignKey(
        Category,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="blogs",
        db_index=True,
    )
    tags = models.ManyToManyField(Tag, blank=True, related_name="blogs")

    # Computed/auto fields
    reading_time = models.PositiveIntegerField(default=1, help_text="Estimated reading time in minutes")
    views_count = models.PositiveIntegerField(default=0, db_index=True)

    class Meta:
        verbose_name = "Blog"
        verbose_name_plural = "Blogs"
        ordering = ["-publish_date", "-created_at"]
        indexes = [
            models.Index(fields=["status", "publish_date"]),
            models.Index(fields=["status", "category"]),
            models.Index(fields=["slug"]),
        ]

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = self._generate_unique_slug()
        self.reading_time = self._calculate_reading_time()
        if self.status == BlogStatus.PUBLISHED and not self.publish_date:
            self.publish_date = timezone.now()
        
        # Auto-populate canonical URL if empty
        if not self.canonical_url and self.slug:
            self.canonical_url = f"https://www.pestcontrol99.com/blog/{self.slug}/"
            
        super().save(*args, **kwargs)

    def _generate_unique_slug(self):
        base_slug = slugify(self.title)[:480]
        slug = base_slug
        counter = 1
        while Blog.objects.filter(slug=slug).exclude(pk=self.pk).exists():
            slug = f"{base_slug}-{counter}"
            counter += 1
        return slug

    def _calculate_reading_time(self):
        import re
        text = re.sub(r"<[^>]+>", " ", self.content)
        word_count = len(text.split())
        minutes = max(1, round(word_count / 200))
        return minutes

    @property
    def is_published(self):
        return self.status == BlogStatus.PUBLISHED

    @property
    def keywords_list(self):
        if not self.target_keywords:
            return []
        return [kw.strip() for kw in self.target_keywords.split(",") if kw.strip()]


class BlogAuditLog(BaseModel):
    """Audit trail for blog CMS actions (content writers, publishes, uploads)."""

    class Action(models.TextChoices):
        LOGIN = 'login', 'Login'
        CREATED = 'blog_created', 'Blog Created'
        EDITED = 'blog_edited', 'Blog Edited'
        PUBLISHED = 'blog_published', 'Blog Published'
        UNPUBLISHED = 'blog_unpublished', 'Blog Unpublished'
        DELETED = 'blog_deleted', 'Blog Deleted'
        IMAGE_UPLOADED = 'image_uploaded', 'Image Uploaded'

    user = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='blog_audit_logs',
    )
    action = models.CharField(max_length=32, choices=Action.choices, db_index=True)
    blog = models.ForeignKey(
        Blog,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='audit_logs',
    )
    details = models.TextField(blank=True)
    ip_address = models.GenericIPAddressField(null=True, blank=True)
    user_agent = models.CharField(max_length=512, blank=True)

    class Meta:
        ordering = ['-created_at']
        verbose_name = 'Blog Audit Log'
        verbose_name_plural = 'Blog Audit Logs'

    def __str__(self):
        who = self.user.username if self.user else 'unknown'
        return f'{who} — {self.action} — {self.created_at}'
