# Generated by Django 4.2.7 on 2026-05-13 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0059_city_country_jobcard_booking_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Full Name')),
                ('mobile', models.CharField(max_length=15, unique=True, verbose_name='Mobile Number')),
                ('password', models.CharField(max_length=255, verbose_name='Password (hashed)')),
                ('role', models.CharField(choices=[('technician', 'Technician'), ('technician_admin', 'Technician Admin')], default='technician', max_length=30, verbose_name='Role')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='partner_profiles/', verbose_name='Profile Image')),
                ('fcm_token', models.TextField(blank=True, help_text='Firebase Cloud Messaging token for push notifications', null=True, verbose_name='FCM Push Token')),
                ('bank_name', models.CharField(blank=True, max_length=200, null=True)),
                ('account_number', models.CharField(blank=True, max_length=30, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=20, null=True)),
                ('account_holder_name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('core_technician', models.OneToOneField(blank=True, help_text='Links this partner account to the CRM technician record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_account', to='core.technician', verbose_name='CRM Technician Record')),
            ],
            options={
                'verbose_name': 'Partner',
                'verbose_name_plural': 'Partners',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PartnerRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=5, verbose_name='Rating (1-5)')),
                ('feedback', models.TextField(blank=True, null=True, verbose_name='Customer Feedback')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_ratings', to='core.jobcard', verbose_name='Job')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='partner.partner', verbose_name='Partner')),
            ],
            options={
                'verbose_name': 'Partner Rating',
                'verbose_name_plural': 'Partner Ratings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PartnerEarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Earning Amount')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_earnings', to='core.jobcard', verbose_name='Job')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to='partner.partner', verbose_name='Partner')),
            ],
            options={
                'verbose_name': 'Partner Earning',
                'verbose_name_plural': 'Partner Earnings',
                'ordering': ['-created_at'],
            },
        ),
    ]
