# Generated by Django 4.2.7 on 2026-05-19 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_userprofile_technician_role'),
        ('partner', '0003_partnerrevokedjti'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('new_booking', 'New Booking'), ('booking_assigned', 'Booking Assigned'), ('booking_accepted', 'Booking Accepted'), ('booking_cancelled', 'Booking Cancelled'), ('complaint_call', 'Complaint Call'), ('service_reminder', 'Service Reminder'), ('amc_followup', 'AMC Follow-up'), ('payment_pending', 'Payment Pending'), ('job_completed', 'Job Completed'), ('general', 'General')], db_index=True, default='general', max_length=40)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_notifications', to='core.jobcard')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='partner.partner')),
            ],
            options={
                'verbose_name': 'Partner Notification',
                'verbose_name_plural': 'Partner Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CrmPartnerEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('booking_sent_to_app', 'Sent To App'), ('booking_accepted', 'Booking Accepted'), ('service_started', 'Service Started'), ('job_completed', 'Job Completed'), ('booking_rejected', 'Booking Rejected')], db_index=True, max_length=40)),
                ('message', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_partner_events', to='core.jobcard')),
            ],
            options={
                'verbose_name': 'CRM Partner Event',
                'verbose_name_plural': 'CRM Partner Events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PartnerDeviceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fcm_token', models.CharField(db_index=True, max_length=512, unique=True)),
                ('device_type', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS')], default='android', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('last_used_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_tokens', to='partner.partner')),
            ],
            options={
                'verbose_name': 'Partner Device Token',
                'verbose_name_plural': 'Partner Device Tokens',
                'indexes': [models.Index(fields=['partner', 'is_active'], name='partner_par_partner_5156c0_idx')],
            },
        ),
    ]
